version: "3.4"

services:
  web:
    image: richarvey/nginx-php-fpm
    ports:
      - "5000:80"
    volumes:
      - ./Public:/var/www/html
      - ./conf.d:/conf/nginx/
    networks: 
      - web-net
networks: 
  web-net: