version: "3.4"

services:
  web:
    image: richarvey/nginx-php-fpm
    ports:
      - "5000:80"
    volumes:
      - ./Public:/var/www/html
      - ./conf.d:/conf/nginx/
    networks: 
      - web-net
    deploy:
      mode: global
    depends_on:
      - db 
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks: 
      - web-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
    networks: 
      - web-net
  redis:
    image: redis
    networks: 
      - web-net
networks: 
  web-net: