version: "3.4"
  services:
    mysql:
      image: mysql:latest
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
        restart_policy:
          condition: on-failure
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_USER: admin
        MYSQL_PASSWORD: password
    php:
      image: wiput1999/php
      volumes:
        - ./public:/web
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./public:/code:ro
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf