web:
  image: nginx:latest
  ports:
      - "80:80"
  volumes:
      - ./public:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/site.conf
  links:
      - php
php:
  image: php:7-fpm
  volumes:
      - ./code:/code