version: "3.4"

services:
  web:
    image: nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5000:80"
    volumes:
        - ./code:/code