version: "3.4"

services:
  web:
    image: nginx
    ports:
        - "80:80"
    volumes:
      - ./Public:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-net
  php:
    image: php
    volumes:
      - ./Public:/code
    networks:
      - nginx-net

networks:
  nginx-net: