version: "3.4"

services:
  mysql:
    image: mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  php:
    image: php
    ports:
        - "9000:9000"
    volumes:
      - ./Public:/web
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Public:/web
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mysql