version: "2"

services:
  web:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./Public:/public_html
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginxphp
  php:
    image: php
    volumes:
      - ./Public:/public_html
    expose:
      - 9000
    networks:
      - nginxphp
networks:
  nginxphp: