version: "3.4"

services:
  nginx:
    image: nginx
    links:
      - php
    ports:
        - "80:80"
    volumes:
        - ./Config/default:/etc/nginx/sites-available/default
        - ./Config/default:/etc/nginx/sites-enabled/default

        - ./Logs/nginx-error.log:/var/log/nginx/error.log
        - ./Logs/nginx-access.log:/var/log/nginx/access.log
    networks: 
      - nginx-net
  php:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./Public:/usr/share/nginx/html
    networks: 
      - nginx-net
networks:
  nginx-net: