version: "3.4"

services:
  web:
    image: nginx
    ports:
        - "80:80"
    networks:
      - nginx-net
    depends_on:
      - php
  php:
    image: php
    ports:
      - "3000:3000"
    networks: 
      - nginx-net
networks:
  nginx-net: