version: "3.4"

services:
  web:
    image: nginx
    ports:
        - "80:80"
    volumes:
      - ./Public:/code
      - ./default.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
networks:
  nginx-net: