version: "3.4"

services:
  nginx:
    image: nginx
    ports:
        - "80:80"
    links:
        - php
    volumes:
    #    - ./Config/nginx:/etc/nginx/sites-available/default
    #    - ./Config/nginx:/etc/nginx/sites-enabled/default

    #    - ./Logs/nginx-error.log:/var/log/nginx/error.log
    #   - ./Logs/nginx-access.log:/var/log/nginx/access.log
  php:
    image: php:fpm
      ports:
          - "9000:9000"
      volumes:
          - ./Public:/usr/share/nginx/html
  #mysql:
  #  image: mariadb
  #  environment:
  #    MYSQL_ROOT_PASSWORD: admin
  #  ports:
  #    - "3306:3306"
  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  restart: always
  #  links:
  #    - mysql
  #  ports:
  #    - 8183:80
  #  environment:
  #    PMA_USER: root
  #    PMA_PASSWORD: admin
  #    PMA_ARBITRARY: 1
